#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm backup"
}

core() {
  swarm::backup "$@"
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core "$@"
}

run "$@"
