#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm exec <service> [options]"
}

core() {
  local service=$1
  local command=${@:2}

  swarm::exec $service $command
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
