#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm list [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  export ZMICRO_SERVICES_PATH=$SWARM_PLUGIN_SERVICE_PATH
  service::list $@
}

run() {
  core $@
}

run $@
