#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm ls [options...]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zswarm list
}

run() {
  core $@
}

run $@
