#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm ps <service> [options]"
  echo ""
  echo "Options:"
  echo "  -d, --detail  Show the detail info"
  echo "  --no-trunc    Same as --detail"
  echo " -h, --help     Show this help"
}

core() {
  local service=$1
  local args="${@:2}"
  if [ "$service" = "" ]; then
    log::error "service is required"
    exit 1
  fi

  swarm::ps $service $args
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
