#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm register <SWARM_SERVICE_PATH>"
}

core() {
  local service_path=$1
  if [ "$service_path" = "" ]; then
    log::error "swarm service path is required"
    exit 1
  fi

  swarm::register $service_path
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
