#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm status [options]"
}

core() {
  swarm::status $@
}

run() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  core $@
}

run $@
