#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm update"
  echo ""
  echo "    -h, --help              Get help"
  echo "    -u, --update <version>  Set new version"
}

core() {
  local service=$1
  if [ "$service" = "" ]; then
    log::error "service is required"
    exit 1
  fi

  cd $PLUGIN_SWARM_SERVICE/$service
  if [ ! -f .env ]; then
    log::error "Please use .env instead of write all config in docker-compose.yml"
    exit 1
  fi

  . .env
  local old_version=$VERSION

  # vim .env

  . .env
  local new_version=$VERSION
  if [ "$old_version" = "$new_version" ]; then
    log::info "No version change for $service"
    exit 0
  fi

  log "[service: $(color::success $service)]: version update $(color::error $old_version) => $(color::success $new_version)"
  swarm::restart $service
}

run() {
  core $@
}

run $@
