#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm version <service>"
  echo ""
  echo "    -h, --help              Get help"
  echo "    -u, --update <version>  Set new version"
}

core() {
  local service=$1
  if [ "$service" = "" ]; then
    log::error "service is required"
    exit 1
  fi

  swarm::version $service
}

run() {
  core $@
}

run $@
