#!/bin/bash

h_load() {
  if [ ! -d $ZMICRO_LOG_PATH ] || [ ! -w $ZMICRO_LOG_COMMON_PATH ]; then
    . $CORE_PATH/log
    log_init
  fi

  log_debug "[CORE] load $1"

  local FN_PATH=$SWARM_PLUGIN_CORE_PATH/$1

  if [ -f $FN_PATH ]; then
    . $FN_PATH
  elif [ -d $FN_PATH ]; then
    . $FN_PATH/export
  fi
}

h_load run
